<?php require_once './template/layout/header.phtml'; ?>
<h1>Alerta: </h1>
    <h3>Al borrar una categoria, se van a borrar todos los juegos que utilicen dicho elemento</h3>
    <div>
        <h2> Estas seguro de querer borrar la categoria <?php echo "$categoria->categoría" ?>? </h2>
        <a href="<?= BASE_URL ?>borrarCat/<?= $categoria->ID_cat ?>" class="btn btn-secondary">Sí, eliminar</a>
    </div>
    <a href='<?= BASE_URL ?>home' class='btn btn-primary'>No, volver al inicio</a>

<?php require_once "./template/layout/footer.phtml"; ?>

