<?php require_once './template/layout/header.phtml'; ?>
<h2>Categorías: </h2>
    <?php foreach ($categorias as $categoria): ?>
        <div>
        <?php if($this->user): ?>
            <a href="<?= BASE_URL ?>juegosPorCategoria/<?= $categoria->ID_cat ?>">
                <?= htmlspecialchars($categoria->categoría) ?>
            </a>
        <?php else: ?>
            <a href="<?= BASE_URL ?>juegosPorCategoria/<?= $categoria->ID_cat ?>" class="btn btn-danger">
                <?= htmlspecialchars($categoria->categoría) ?>
            </a>
        <?php endif; ?>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>showModifCat/<?= $categoria->ID_cat ?>" class="btn btn-secondary">Editar la Categoria</a>
            <?php endif; ?>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>showBorrarCat/<?= $categoria->ID_cat ?>" class="btn btn-danger">Borrar la Categoria</a>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <?php if($this->user): ?>
        <a href='<?= BASE_URL ?>showNuevaCat' class='btn btn-primary'>Crear una nueva Categoría</a>
    <?php endif; ?>
<a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al menu principal</a>

<?php require_once "./template/layout/footer.phtml"; ?>

