<?php require_once './template/layout/header.phtml'; ?>
    <article>
        <div>
            <h1> <?php echo $juego->nombre; ?> </h1>
            <h2>Plataforma: <?php echo $juego->ID_plat; ?></h2>
            <h2>Descripcion</h2>
            <p class="descripcion"> <?php echo $juego->descripción; ?> </p>
        </div>
        <img class="imagen-objeto" src=" <?php echo $juego->imagen; ?>" alt="img">
    </article>
<?php require_once './template/layout/footer.phtml'; ?>
