<?php
require_once './template/layout/header.phtml';
?>
<div class="container text-center mt-5">
    <div class="error-container">
        <h1 class="display-1 text-danger">Error 404</h1>
        <p class="lead">La pagina no existe.</p>
        <a class="btn btn-primary" href="<?php echo BASE_URL; ?>">Volver a la página de inicio</a>
    </div>
</div>
<?php
require_once './template/layout/footer.phtml';
?>
