<?php
    require_once 'template/layout/header.phtml';
?>
<form method="POST" action="nuevoJuego" class="container mt-4">
    <h2>Crear un nuevo juego: </h2>
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre del juego" required>
    </div>
    <div class="mb-3">
        <label for="imagen" class="form-label">Imagen (URL)</label>
        <input type="text" name="imagen" class="form-control" id="imagen" placeholder="Imagen a usar (agregar una URL)" required>
    </div>
    <div class="mb-3">
        <label for="descripción" class="form-label">Descripción</label>
        <input type="text" name="descripción" class="form-control" id="descripción" placeholder="Descripción" required>
    </div>
    <div class="mb-3">
        <label for="ID_usuario" class="form-label">ID_usuario</label>
        <input type="number" name="ID_usuario" class="form-control" id="ID_usuario" placeholder="ID_usuario" required>
    </div>
    <div class="mb-3">
        <label for="ID_plat" class="form-label">ID_plat</label>
        <input type="number" name="ID_plat" class="form-control" id="ID_plat" placeholder="ID_plat" required>
    </div>
    <div class="mb-3">
        <label for="ID_cat" class="form-label">ID_cat</label>
        <input type="number" name="ID_cat" class="form-control" id="ID_cat" placeholder="ID_cat" required>
    </div>
    <?php /*<select name="categoria" id="categoria">

        <?php foreach($categoria as $cat){ ?>
                <?php echo $cat-> categoría; ?>
        <?php } ?>
    </select>

    </div>
    <div class="mb-3">
        <?php foreach($plataforma as $plat){ ?>
            <select name="plataforma" id="plataforma">
                <?php echo $plat->consola; ?>
            </select>
        <?php } ?>
    </div>  */ ?>
    <button type="submit" class="btn btn-primary">Agregar Juego Nuevo</button>
</form>
<?php
    require_once './template/layout/footer.phtml';
?>

