<?php
    require_once 'template/layout/header.phtml';
?>
<form method="POST" action="<?= BASE_URL ?>modifCat" class="container mt-4">
    <h2>Modificar Categoría: </h2>
    <input type="hidden" name="ID_cat" value="<?= $categoria->ID_cat; ?>">
    <div class="mb-3">
        <label for="categoría" class="form-label">Categoría</label>
        <input type="text" name="categoría" class="form-control" id="categoría" placeholder="categoría a editar" value="<?= $categoria->categoría; ?>" required>
    </div>
    <button type="submit" class="btn btn-primary">Modificar la categoria</button>
    <a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al inicio</a>
</form>

<?php
    require_once './template/layout/footer.phtml';
?>

