<?php
    require_once 'template/layout/header.phtml';
?>
<form method="POST" action="nuevoJuego" class="container mt-4">
    <h2>Modificar el juego: <?php echo $juego->nombre ?> </h2>
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre del juego" required>
    </div>
    <div class="mb-3">
        <label for="imagen" class="form-label">Imagen (URL)</label>
        <input type="text" name="imagen" class="form-control" id="imagen" placeholder="Imagen a usar (agregar una URL)" required>
    </div>
    <div class="mb-3">
        <label for="descripción" class="form-label">Descripción</label>
        <input type="text" name="descripción" class="form-control" id="descripción" placeholder="Descripción" required>
    </div>

    <div class="mb-3">
    <select class="form-control" name="ID_plat" required>
        
        <?php foreach($plataforma as $plat){ ?>
 
         <option type="number" id="ID_plat"  value=<?=$plat->ID_plat?>> <?=$plat->consola?> </option>

        <?php } ?> 

    </select> 
        </div>
        <div class="mb-3">
     <select class="form-control" name="ID_cat" required>
        
        <?php foreach($categoria as $cat){ ?>
 
         <option type="number" id="ID_cat"  value=<?=$cat->ID_cat?>> <?=$cat->categoría?> </option>

        <?php } ?> 

    </select> 
        </div>
    <button type="submit" class="btn btn-primary">Agregar Juego Modificado</button>
    <a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al inicio</a>
</form>

<?php
    require_once './template/layout/footer.phtml';
?>

