<?php
    require_once 'template/layout/header.phtml';
?>
<form method="POST" action="nuevaPlat" class="container mt-4">
    <h2>Crear una nueva plataforma: </h2>
    <div class="mb-3">
        <label for="consola" class="form-label">consola</label>
        <input type="text" name="consola" class="form-control" id="consola" placeholder="Nueva Consola" required>
    </div>
    <button type="submit" class="btn btn-primary">Agregar Nueva Plataforma</button>
    <a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al inicio</a>
</form>

<?php
    require_once './template/layout/footer.phtml';
?>

