<?php require_once './template/layout/header.phtml'; ?>
<article class="seccion-juegos">
    <?php foreach($juegos as $juego){  ?>
        <div class="objeto">
            <img class="imagen-objeto" id="imagen-detalle" src=" <?php echo $juego->imagen; ?>" alt="img">
            <h1> <?php echo $juego->nombre; ?> </h1>
            <p> <?php echo $juego->ID_plat; ?></p>
        </div>
    <?php } ?>
</article>

<?php require_once "./template/layout/footer.phtml"; ?>
