<?php require_once './template/layout/header.phtml'; ?>
<article class="seccion-juegos">
    <?php foreach($juegos as $juego){  ?>
        <div class="objeto">
            <img class="imagen-objeto" id="imagen-detalle" src=" <?php echo $juego->imagen; ?>" alt="img">
            <h1> <?php echo $juego->nombre; ?> </h1>
            <a href="<?= BASE_URL ?>juego/<?= $juego->ID_juego ?>" class="btn btn-secondary">Ver Detalles</a>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>showModifJuego/<?= $juego->ID_juego ?>" class="btn btn-secondary">Modificar Juego</a>
            <?php endif; ?>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>borrarJuego/<?= $juego->ID_juego ?>" class="btn btn-secondary">Borrar Juego</a>
            <?php endif; ?>
        </div>
    <?php } ?>
    <a href='<?= BASE_URL ?>listaCategoria' class='btn btn-primary'>Volver a la Lista</a>
</article>

<?php require_once "./template/layout/footer.phtml"; ?>