<?php require_once './template/layout/header.phtml'; ?>

<h1>Plataformas: </h1>
    <?php foreach ($plataformas as $plataforma): ?>
        <div>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>juegosPorPlataforma/<?= $plataforma->ID_plat ?>">
                    <?= htmlspecialchars($plataforma->consola) ?>
                </a>
            <?php else: ?>
                <a href="<?= BASE_URL ?>juegosPorPlataforma/<?= $plataforma->ID_plat ?>"class="btn btn-danger">
                    <?= htmlspecialchars($plataforma->consola) ?>
                </a>
            <?php endif; ?>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>showModifPlat/<?= $plataforma->ID_plat ?>" class="btn btn-secondary">Editar la Plataforma</a>
            <?php endif; ?>
            <?php if($this->user): ?>
                <a href="<?= BASE_URL ?>showBorrarPlat/<?= $plataforma->ID_plat ?>" class="btn btn-danger">Borrar la Consola</a>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <?php if($this->user): ?>
        <a href='<?= BASE_URL ?>showNuevaPlat' class='btn btn-primary'>Crear una nueva plataforma</a>
    <?php endif; ?>
<a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al menú principal</a>


<?php require_once "./template/layout/footer.phtml"; ?>

