<?php require_once './template/layout/header.phtml'; ?>

<h2>Plataformas</h2>
<ul>
    <?php foreach ($plataformas as $plataforma): ?>
        <li>
        <a href="<?= BASE_URL . 'juegosPorPlataforma' . $plataforma->$ID_plataforma ?>">
                <?= htmlspecialchars($plataforma->consola) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al menu principal</a>


<?php require_once "./template/layout/footer.phtml"; ?>