<?php require_once './template/layout/header.phtml'; ?>
<h2>Categorías</h2>
<ul>
    <?php foreach ($categorias as $categoria): ?>
        <li>
            <a href="<?= BASE_URL . 'juegosPorCategoria' . $categoria->ID_categoria ?>">
                <?= htmlspecialchars($categoria->categoría) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al menu principal</a>

<?php require_once "./template/layout/footer.phtml"; ?>
