<?php require_once './template/layout/header.phtml'; ?>

<?php if($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method="post" action="signup">
    <div class="form-group">
        <label for="usuario">usuario</label>
        <input type="text" class="form-control" id="usuario" name="usuario" required>
    </div>
    <div class="form-group">
        <label for="password">contraseña</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Registrarse</button>
</form>
<a href='<?= BASE_URL ?>home' class='btn btn-primary'>Volver al menu principal</a>


<?php require_once "./template/layout/footer.phtml"; ?>
