<?php require_once './template/layout/header.phtml'; ?>
<article class="seccion-juegos">
    <?php foreach($juegos as $juego){  ?>
        <div class="objeto">
            <img class="imagen-objeto" id="imagen-detalle" src=" <?php echo $juego->imagen; ?>" alt="img">
            <h1> <?php echo $juego->nombre; ?> </h1>
            <?php /* 
            <p> <?php echo $plataformas->consola; ?></p>
            <p> <?php echo $categorias->categoría; ?></p> 
            */ ?>
            <a href="<?= BASE_URL ?>juego/<?= $juego->ID_juego ?>" class="btn btn-secondary">Ver Detalles</a>
        </div>
    <?php } ?>
</article>

<?php require_once "./template/layout/footer.phtml"; ?>
