<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="<?php echo BASE_URL . 'public/img/elmagoroms.png'; ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="<?php echo BASE_URL . './public/css/style.css'; ?>">
    <title>El MaGo Roms</title>
</head>
<body>
    <header>
        <a href='<?= BASE_URL ?>home'>
            <div class="header-espacio">
                <h1>El MaGo Roms</h1>
            </div>
        </a>
        <img class="imagen-logo" src="<?php echo BASE_URL . 'public/img/elmagoroms.png'; ?>" alt="Logo El Mago Roms">     
        <div class="header-espacio">
            <a href='<?= BASE_URL ?>listaCategoria' class='btn btn-primary'>Géneros</a>
            <a href='<?= BASE_URL ?>listaPlataforma' class='btn btn-primary'>Plataformas</a>
            <?php if($this->user): ?>
                <a href='<?= BASE_URL ?>logout' class="btn btn-danger">Salir</a>
            <?php else: ?>
                <a href='<?= BASE_URL ?>showLogin' class='btn btn-primary'>Iniciar Sesion</a>
                <a href='<?= BASE_URL ?>showSignup' class='btn btn-primary'>Crear Cuenta</a>
            <?php endif; ?>
        </div>
    </header>


